spring:
  application:
    name: task-api
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      timeout: 5s
      connect-timeout: 5s
      database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.taskhub.auto.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

security:
  jwt:
    secret: task-api-secret-key-task-api-secret-key-2026
    issuer: task-api
    access-token-expire-seconds: 7200

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
